# Generated by Django 4.2.1 on 2023-06-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromodel',
            options={'permissions': [('puede_ver_usuarios', 'Permiso para ver usuarios')]},
        ),
    ]
