# Generated by Django 4.2.1 on 2023-06-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_alter_registromodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromodel',
            options={'permissions': [('puede_ver_usuarios', 'Permiso para ver usuarios'), ('puede_ver_pagina', 'Permiso para ver pagina')]},
        ),
    ]
